export const SIGN_IN = 'AUTH/SIGN_IN';
export const SIGN_OUT = 'AUTH/SIGN_OUT';
export const SHOW_MESSAGE = 'AUTH/SHOW_MESSAGE';
export const HIDE_MESSAGE = 'AUTH/HIDE_MESSAGE';
export const UPDATE_ORDERS = 'ORDER/UPDATE_ORDERS';
export const CHANGE_CURRENT_ORDER = 'ORDER/CHANGE_CURRENT_ORDER';
export const UPDATE_FUTURE_JOB_TYPES = 'ORDER/UPDATE_FUTURE_JOB_TYPES';